version: '3'
services:
  listing:
    build: .
    image: my-listings-app
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - ./:/app/listing-app
      - /app/listing-app/node_modules
  mongo:
     image: mongo
     volumes:
       - ./data:/data/db
     ports:
       - "27017:27017"

